import type { WeatherAlert, WeatherAlertPreference, WeatherSnapshot } from '@/types/dashboard';

export const MOCK_WEATHER: WeatherSnapshot = {
  temperatureF: 72,
  condition: 'Partly Cloudy',
  highF: 78,
  lowF: 58,
  humidity: 45,
  windMph: 8,
  locationLabel: 'Your area',
};

export const MOCK_ALERTS: WeatherAlert[] = [
  {
    id: '1',
    severity: 'MODERATE',
    title: 'Flood Watch',
    location: 'CHEYENNE RIVER ABOVE ANGOSTURA AT HWY 71, SD',
    source: 'NWPS',
    issuedAgo: 'Issued less than a minute ago',
    expires: 'EXPIRES: SEE GAUGE / NWPS',
    read: false,
  },
  {
    id: '2',
    severity: 'MODERATE',
    title: 'Flood Watch',
    location: 'CHEYENNE RIVER ABOVE ANGOSTURA AT HWY 71, SD',
    source: 'NWPS',
    issuedAgo: 'Issued 12 minutes ago',
    expires: 'EXPIRES: SEE GAUGE / NWPS',
    read: false,
  },
  {
    id: '3',
    severity: 'LOW',
    title: 'Wind Advisory',
    location: 'WESTERN PLAINS REGION',
    source: 'NWS',
    issuedAgo: 'Issued 1 hour ago',
    expires: 'EXPIRES: 6:00 PM LOCAL',
    read: true,
  },
];

/**
 * Offline/fallback catalog — mirrors backend `NWS_WEATHER_ALERT_TYPES`.
 * Live list comes from GET /weather/preferences.
 */
export const DEFAULT_WEATHER_ALERT_PREFERENCES: WeatherAlertPreference[] = [
  {
    id: 'tornado_warning',
    label: 'Tornado Warning',
    description: 'Immediate danger — a tornado has been sighted or indicated by radar.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'tornado_watch',
    label: 'Tornado Watch',
    description: 'Conditions favor tornadoes. Stay weather-aware.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'severe_thunderstorm_warning',
    label: 'Severe Thunderstorm Warning',
    description: 'Damaging winds or large hail are occurring or imminent.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'severe_thunderstorm_watch',
    label: 'Severe Thunderstorm Watch',
    description: 'Severe thunderstorms are possible in your area.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'flash_flood_warning',
    label: 'Flash Flood Warning',
    description: 'Life-threatening flash flooding is occurring or imminent.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'flash_flood_watch',
    label: 'Flash Flood Watch',
    description: 'Flash flooding is possible. Be ready to move to higher ground.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'flood_warning',
    label: 'Flood Warning',
    description: 'Flooding is occurring or imminent along rivers or streams.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'flood_watch',
    label: 'Flood Watch',
    description: 'Flooding is possible. Monitor local conditions.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'flood_advisory',
    label: 'Flood Advisory',
    description: 'Minor flooding expected that may inconvenience travel.',
    category: 'Severe',
    enabled: true,
  },
  {
    id: 'blizzard_warning',
    label: 'Blizzard Warning',
    description: 'Blizzard conditions with low visibility and strong winds.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'winter_storm_warning',
    label: 'Winter Storm Warning',
    description: 'Hazardous snow, ice, or sleet is expected or occurring.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'winter_storm_watch',
    label: 'Winter Storm Watch',
    description: 'Significant winter weather is possible.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'winter_weather_advisory',
    label: 'Winter Weather Advisory',
    description: 'Snow, ice, or freezing rain that may cause travel impacts.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'ice_storm_warning',
    label: 'Ice Storm Warning',
    description: 'Damaging ice accumulation expected.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'extreme_cold_warning',
    label: 'Extreme Cold Warning',
    description: 'Dangerously cold temperatures or wind chill.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'freeze_watch',
    label: 'Freeze Watch',
    description: 'Freezing temperatures that may damage crops or pipes are possible.',
    category: 'Winter',
    enabled: true,
  },
  {
    id: 'hurricane_warning',
    label: 'Hurricane Warning',
    description: 'Hurricane conditions expected within 36 hours.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'hurricane_watch',
    label: 'Hurricane Watch',
    description: 'Hurricane conditions are possible within 48 hours.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'tropical_storm_warning',
    label: 'Tropical Storm Warning',
    description: 'Tropical storm conditions expected within 36 hours.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'tsunami_warning',
    label: 'Tsunami Warning',
    description: 'A tsunami with significant inundation is imminent or expected.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'coastal_flood_warning',
    label: 'Coastal Flood Warning',
    description: 'Coastal flooding is occurring or imminent.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'coastal_flood_advisory',
    label: 'Coastal Flood Advisory',
    description: 'Minor coastal flooding expected.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'special_marine_warning',
    label: 'Special Marine Warning',
    description: 'Sudden marine hazards such as thunderstorms or waterspouts.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'small_craft_advisory',
    label: 'Small Craft Advisory',
    description: 'Hazardous conditions for small boats.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'rip_current_statement',
    label: 'Rip Current Statement',
    description: 'Dangerous rip currents along beaches.',
    category: 'Coastal',
    enabled: true,
  },
  {
    id: 'fire_weather_warning',
    label: 'Red Flag Warning',
    description: 'Critical fire weather conditions — high risk of rapid fire growth.',
    category: 'Fire/Heat',
    enabled: true,
  },
  {
    id: 'fire_weather_watch',
    label: 'Fire Weather Watch',
    description: 'Critical fire weather conditions are possible.',
    category: 'Fire/Heat',
    enabled: true,
  },
  {
    id: 'excessive_heat_warning',
    label: 'Excessive Heat Warning',
    description: 'Dangerously hot conditions that can cause heat illness.',
    category: 'Fire/Heat',
    enabled: true,
  },
  {
    id: 'heat_advisory',
    label: 'Heat Advisory',
    description: 'Hot conditions that may cause heat-related illness.',
    category: 'Fire/Heat',
    enabled: true,
  },
  {
    id: 'high_wind_warning',
    label: 'High Wind Warning',
    description: 'Damaging high winds expected or occurring.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'high_wind_watch',
    label: 'High Wind Watch',
    description: 'Damaging high winds are possible.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'wind_advisory',
    label: 'Wind Advisory',
    description: 'Strong winds that may create travel or outdoor hazards.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'lake_wind_advisory',
    label: 'Lake Wind Advisory',
    description: 'Strong winds expected over lakes.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'dust_storm_warning',
    label: 'Dust Storm Warning',
    description: 'Blinding dust with sudden low visibility.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'air_quality_alert',
    label: 'Air Quality Alert',
    description: 'Unhealthy air quality for sensitive groups or the public.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'air_stagnation_advisory',
    label: 'Air Stagnation Advisory',
    description: 'Limited air movement that may trap pollutants.',
    category: 'Other',
    enabled: true,
  },
  {
    id: 'special_weather_statement',
    label: 'Special Weather Statement',
    description: 'Notable weather that does not meet watch/warning criteria.',
    category: 'Other',
    enabled: true,
  },
];
